version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse

    steps:
      - checkout

      - run:
          name: Get the data
          command: |
             R -q -e "rmarkdown::render('index.Rmd',output_file='index.html')"

workflows:
    version: 2
    weekly:
        jobs:
            - update-and-publish
        triggers:
            - schedule:
                cron: 10 10 * * *
                filters:
                    branches:
                        only:
                            - master
